/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zExperiment;

import fads.original.OFADS;
import fads.varied.VFADS;

/**
 *
 * @author 77781225
 */
public class StreamExperiment extends javax.swing.JFrame {

    /**
     * Creates new form StreamExperiment
     */
    public StreamExperiment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        ntupleLabel = new javax.swing.JLabel();
        kdegreeLabel = new javax.swing.JLabel();
        deltaLabel = new javax.swing.JLabel();
        omegaLabel = new javax.swing.JLabel();
        ntupleField = new javax.swing.JTextField();
        kdegreeField = new javax.swing.JTextField();
        deltaField = new javax.swing.JTextField();
        omegaField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        algoCombo = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Experiments");
        setLocationByPlatform(true);

        startButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        ntupleLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ntupleLabel.setText("Number of tuples:");

        kdegreeLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kdegreeLabel.setText("Anonymity degree:");

        deltaLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deltaLabel.setText("Allowed time of tuple:");

        omegaLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        omegaLabel.setText("Allowed time of cluster:");

        ntupleField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        kdegreeField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        deltaField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        omegaField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameLabel.setText("Algorithm name: ");

        algoCombo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        algoCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FADS-Original", "FADS-Varied", "CASTLE-Original", "CASTLE-Varied" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(kdegreeLabel)
                        .addComponent(deltaLabel)
                        .addComponent(omegaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ntupleLabel)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deltaField)
                    .addComponent(omegaField)
                    .addComponent(ntupleField, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(kdegreeField)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(algoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {algoCombo, deltaField, kdegreeField, ntupleField, omegaField});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deltaLabel, kdegreeLabel, nameLabel, ntupleLabel, omegaLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(algoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ntupleLabel)
                    .addComponent(ntupleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kdegreeLabel)
                    .addComponent(kdegreeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deltaLabel)
                    .addComponent(deltaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(omegaLabel)
                    .addComponent(omegaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(exitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {algoCombo, deltaField, kdegreeField, ntupleField, omegaField});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {deltaLabel, kdegreeLabel, ntupleLabel, omegaLabel});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {exitButton, startButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
       System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        int N;//ntuple
        int K;//kdegree
        int D;//delta time
        int O;//omega time
        
        String algoName=algoCombo.getSelectedItem().toString();
        N=Integer.parseInt(ntupleField.getText());
        K=Integer.parseInt(kdegreeField.getText());
        D=Integer.parseInt(deltaField.getText());
        O=Integer.parseInt(omegaField.getText());
        
        if(algoName.equals("FADS-Original")){
            OFADS f=new OFADS(N, K, D, O);
            f.StartAll();
        }
        
        if(algoName.equals("FADS-Varied")){
            VFADS f=new VFADS(N, K, D, O);
            f.StartAll();
        }
        
        
        
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StreamExperiment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StreamExperiment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StreamExperiment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StreamExperiment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StreamExperiment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> algoCombo;
    private javax.swing.JTextField deltaField;
    private javax.swing.JLabel deltaLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField kdegreeField;
    private javax.swing.JLabel kdegreeLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField ntupleField;
    private javax.swing.JLabel ntupleLabel;
    private javax.swing.JTextField omegaField;
    private javax.swing.JLabel omegaLabel;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
